# ansible/inventory.ini
# Replace APP_VM_EXTERNAL_IP and MONITORING_VM_EXTERNAL_IP with terraform outputs:
#   terraform output vm_external_ip
#   terraform output monitoring_vm_external_ip

[app]
travel-vm ansible_host=APP_VM_EXTERNAL_IP ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/id_rsa

[monitoring]
monitoring-vm ansible_host=MONITORING_VM_EXTERNAL_IP ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
